// Code generated by goyacc -o tools/syz-trace2syz/parser/strace.go -p Strace -v= tools/syz-trace2syz/parser/strace.y. DO NOT EDIT.

//line tools/syz-trace2syz/parser/strace.y:2
// Copyright 2018 syzkaller project authors. All rights reserved.
// Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.

//go:build !codeanalysis
// +build !codeanalysis

package parser

import __yyfmt__ "fmt"

//line tools/syz-trace2syz/parser/strace.y:7

//line tools/syz-trace2syz/parser/strace.y:13
type StraceSymType struct {
	yys             int
	data            string
	val_int         int64
	val_double      float64
	val_ret_type    int64
	val_uint        uint64
	val_constant    Constant
	val_identifiers []*BufferType
	val_buf_type    *BufferType
	val_group_type  *GroupType
	val_type        IrType
	val_types       []IrType
	val_syscall     *Syscall
}

const STRING_LITERAL = 57346
const IPV6 = 57347
const IDENTIFIER = 57348
const FLAG = 57349
const DATETIME = 57350
const SIGNAL_PLUS = 57351
const SIGNAL_MINUS = 57352
const MAC = 57353
const INT = 57354
const UINT = 57355
const DOUBLE = 57356
const QUESTION = 57357
const ARROW = 57358
const OR = 57359
const AND = 57360
const LOR = 57361
const TIMES = 57362
const LAND = 57363
const LEQUAL = 57364
const ONESCOMP = 57365
const LSHIFT = 57366
const RSHIFT = 57367
const NOT = 57368
const MINUS = 57369
const PLUS = 57370
const COMMA = 57371
const LBRACKET = 57372
const RBRACKET = 57373
const LBRACKET_SQUARE = 57374
const RBRACKET_SQUARE = 57375
const LPAREN = 57376
const RPAREN = 57377
const EQUALS = 57378
const UNFINISHED = 57379
const RESUMED = 57380
const BPF_MACRO = 57381
const NULL = 57382
const EQUALAT = 57383
const COLON = 57384
const FORWARDSLASH = 57385
const LOWEST = 57386
const NOFLAG = 57387
const NEG = 57388

var StraceToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"STRING_LITERAL",
	"IPV6",
	"IDENTIFIER",
	"FLAG",
	"DATETIME",
	"SIGNAL_PLUS",
	"SIGNAL_MINUS",
	"MAC",
	"INT",
	"UINT",
	"DOUBLE",
	"QUESTION",
	"ARROW",
	"OR",
	"AND",
	"LOR",
	"TIMES",
	"LAND",
	"LEQUAL",
	"ONESCOMP",
	"LSHIFT",
	"RSHIFT",
	"NOT",
	"MINUS",
	"PLUS",
	"COMMA",
	"LBRACKET",
	"RBRACKET",
	"LBRACKET_SQUARE",
	"RBRACKET_SQUARE",
	"LPAREN",
	"RPAREN",
	"EQUALS",
	"UNFINISHED",
	"RESUMED",
	"BPF_MACRO",
	"NULL",
	"EQUALAT",
	"COLON",
	"FORWARDSLASH",
	"LOWEST",
	"NOFLAG",
	"NEG",
}

var StraceStatenames = [...]string{}

const StraceEofCode = 1
const StraceErrCode = 2
const StraceInitialStackSize = 16

//line yacctab:1
var StraceExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const StracePrivate = 57344

const StraceLast = 605

var StraceAct = [...]uint8{
	18, 70, 114, 15, 104, 7, 113, 45, 107, 108,
	47, 10, 106, 11, 29, 30, 149, 131, 43, 32,
	2, 55, 19, 46, 8, 57, 4, 127, 45, 34,
	46, 103, 59, 60, 47, 45, 33, 102, 47, 65,
	112, 67, 31, 56, 12, 6, 68, 66, 75, 76,
	77, 78, 3, 92, 46, 62, 63, 64, 46, 45,
	44, 42, 41, 45, 44, 133, 126, 110, 93, 61,
	5, 79, 80, 81, 82, 83, 84, 85, 48, 49,
	56, 52, 29, 30, 40, 50, 51, 32, 53, 54,
	98, 100, 43, 57, 111, 58, 91, 34, 122, 52,
	27, 35, 26, 39, 33, 38, 53, 54, 128, 28,
	31, 109, 122, 105, 122, 132, 137, 97, 134, 52,
	130, 52, 69, 72, 73, 135, 105, 122, 53, 72,
	73, 139, 94, 138, 122, 122, 144, 137, 74, 122,
	146, 137, 141, 142, 74, 29, 30, 122, 99, 137,
	32, 151, 140, 143, 105, 21, 57, 22, 25, 23,
	34, 95, 24, 29, 30, 86, 1, 33, 32, 72,
	73, 9, 71, 31, 20, 90, 17, 16, 34, 0,
	14, 27, 0, 26, 74, 33, 37, 0, 36, 0,
	28, 31, 120, 123, 0, 0, 0, 0, 124, 125,
	0, 52, 0, 116, 117, 50, 51, 0, 53, 54,
	118, 119, 0, 107, 108, 115, 27, 0, 26, 29,
	30, 150, 0, 0, 32, 28, 120, 123, 0, 121,
	57, 0, 124, 125, 34, 0, 0, 116, 117, 0,
	0, 33, 0, 0, 118, 119, 0, 31, 108, 115,
	27, 0, 26, 29, 30, 148, 0, 0, 32, 28,
	120, 123, 0, 121, 57, 0, 124, 125, 34, 0,
	0, 116, 117, 0, 0, 33, 0, 0, 118, 119,
	0, 31, 0, 115, 27, 0, 26, 0, 0, 147,
	0, 0, 21, 28, 22, 25, 23, 121, 0, 24,
	29, 30, 0, 0, 0, 32, 0, 0, 0, 0,
	0, 20, 0, 0, 0, 34, 0, 14, 27, 0,
	26, 0, 33, 145, 120, 123, 0, 28, 31, 0,
	124, 125, 0, 0, 0, 116, 117, 0, 0, 0,
	0, 0, 118, 119, 0, 0, 0, 115, 27, 0,
	26, 0, 0, 136, 0, 0, 21, 28, 22, 25,
	23, 121, 0, 24, 29, 30, 0, 0, 0, 32,
	0, 0, 0, 0, 0, 20, 0, 0, 0, 34,
	0, 14, 27, 0, 26, 0, 33, 96, 0, 0,
	0, 28, 31, 21, 0, 22, 25, 23, 0, 0,
	24, 29, 30, 0, 0, 0, 32, 0, 0, 0,
	0, 0, 20, 0, 0, 0, 34, 0, 88, 27,
	89, 26, 0, 33, 0, 0, 0, 0, 28, 31,
	21, 0, 22, 25, 23, 0, 0, 24, 29, 30,
	0, 0, 0, 32, 0, 0, 0, 0, 0, 20,
	0, 0, 0, 34, 0, 14, 27, 0, 26, 87,
	33, 0, 0, 0, 0, 28, 31, 21, 0, 22,
	25, 23, 0, 0, 24, 29, 30, 0, 0, 0,
	32, 0, 0, 0, 0, 0, 20, 0, 0, 0,
	34, 0, 14, 27, 0, 26, 0, 33, 13, 120,
	123, 0, 28, 31, 0, 124, 125, 0, 0, 0,
	116, 117, 0, 0, 0, 0, 0, 118, 119, 0,
	0, 0, 115, 27, 0, 26, 21, 0, 22, 25,
	23, 0, 28, 24, 29, 30, 121, 0, 0, 32,
	129, 49, 0, 52, 0, 20, 0, 50, 51, 34,
	53, 54, 27, 101, 26, 0, 33, 0, 0, 0,
	0, 28, 31, 21, 0, 22, 25, 23, 0, 0,
	24, 29, 30, 0, 0, 0, 32, 48, 49, 0,
	52, 0, 20, 0, 50, 51, 34, 53, 54, 27,
	0, 26, 0, 33, 49, 0, 52, 0, 28, 31,
	50, 51, 0, 53, 54,
}

var StracePact = [...]int16{
	14, -32768, 36, 8, 14, -25, 9, 463, 71, -32768,
	151, 68, 26, 25, 559, 18, -32768, -32768, -32768, 560,
	70, -32768, 63, -32768, -32768, -32768, -32768, -32768, 35, -32768,
	-32768, -32768, 133, 133, 133, 559, -32768, 11, -32768, 5,
	-32768, 107, 157, 18, 559, 559, 559, 559, 133, 133,
	133, 133, 133, 133, 133, -32768, -32768, 133, 158, 426,
	389, -32768, 576, 61, -32768, 22, 117, 149, 352, -32768,
	83, -32768, -32768, -32768, 136, -6, -32768, -34, -13, 576,
	181, 79, 79, -32768, 99, 101, 58, -32768, 522, -32768,
	2, -32768, 82, 60, -32768, -32768, 4, 493, 32, -32768,
	-9, -32768, -32768, 207, -32768, 523, 103, -19, -32768, -32768,
	31, 493, 113, 318, -32768, -32768, -32768, -32768, -32768, -32768,
	-32768, -32768, -32768, -32768, -32768, -32768, 493, 559, -32768, 241,
	241, 207, 288, 493, 254, -32768, -32768, -32768, 220, -34,
	576, -32768, -32768, 576, -32768, -20, 186, -32768, -32768, 111,
	-32768, -32768,
}

var StracePgo = [...]uint8{
	0, 166, 1, 177, 0, 22, 12, 2, 6, 3,
	176, 4, 5, 175,
}

var StraceR1 = [...]int8{
	0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 8, 8, 7, 7,
	7, 7, 7, 7, 7, 7, 7, 7, 7, 2,
	2, 2, 12, 12, 12, 9, 9, 9, 9, 9,
	5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
	5, 5, 5, 5, 4, 4, 4, 4, 13, 13,
	13, 11, 11, 11, 6, 6, 6, 6, 10, 10,
	10, 10, 10, 3, 3, 3, 3, 3,
}

var StraceR2 = [...]int8{
	0, 4, 5, 4, 6, 8, 5, 10, 5, 8,
	9, 6, 6, 10, 9, 2, 1, 2, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 2, 0, 3, 2, 1, 1, 1, 1, 2,
	1, 1, 1, 3, 2, 3, 3, 3, 3, 3,
	3, 3, 2, 2, 3, 3, 4, 4, 0, 3,
	2, 1, 1, 3, 1, 3, 3, 3, 3, 3,
	3, 3, 6, 1, 1, 1, 1, 1,
}

var StraceChk = [...]int16{
	-32768, -1, 6, 38, 12, 34, 37, -12, 16, -1,
	-12, 38, 35, 35, 29, -9, -3, -10, -4, -5,
	23, 4, 6, 8, 11, 7, 32, 30, 39, 12,
	13, 40, 17, 34, 27, 30, 37, 35, 37, 35,
	16, 36, 36, -9, 42, 41, 36, 16, 17, 18,
	24, 25, 20, 27, 28, -4, -5, 23, 32, -12,
	-12, 34, -5, -5, -5, -9, 36, 36, -12, 15,
	-2, 15, 12, 13, 27, -9, -9, -9, -9, -5,
	-5, -5, -5, -5, -5, -5, 7, 33, 29, 31,
	-13, 35, 31, -2, 15, 12, 35, 34, 7, 12,
	33, 31, 35, 29, -11, -5, -6, 6, 7, 29,
	7, 34, 36, -8, -7, 29, 17, 18, 24, 25,
	6, 43, -4, 7, 12, 13, 34, 36, -11, 17,
	17, 36, -12, 34, -8, 12, 35, -7, -8, -9,
	-5, -6, -6, -5, -11, 35, -8, 35, 35, 36,
	35, -2,
}

var StraceDef = [...]int8{
	0, -2, 0, 32, 0, 32, 0, 0, 0, 15,
	0, 0, 0, 0, 0, 34, 35, 36, 37, 38,
	0, 73, 74, 75, 76, 77, 32, 32, 0, 40,
	41, 42, 0, 0, 0, 0, 1, 0, 3, 0,
	32, 0, 0, 33, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 39, 52, 0, 0, 0,
	0, 58, 44, 0, 53, 0, 0, 0, 0, 2,
	6, 8, 29, 30, 0, 68, 69, 70, 71, 43,
	45, 46, 47, 49, 50, 51, 0, 54, 0, 55,
	0, 48, 0, 11, 12, 4, 0, 0, 0, 31,
	0, 56, 57, 0, 60, 61, 62, 0, 64, 32,
	0, 0, 0, 0, 16, 18, 19, 20, 21, 22,
	23, 24, 25, 26, 27, 28, 0, 0, 59, 0,
	0, 0, 0, 0, 0, 5, 9, 17, 0, 72,
	43, 67, 65, 66, 63, 0, 0, 14, 10, 0,
	13, 7,
}

var StraceTok1 = [...]int8{
	1,
}

var StraceTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46,
}

var StraceTok3 = [...]int8{
	0,
}

var StraceErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	StraceDebug        = 0
	StraceErrorVerbose = false
)

type StraceLexer interface {
	Lex(lval *StraceSymType) int
	Error(s string)
}

type StraceParser interface {
	Parse(StraceLexer) int
	Lookahead() int
}

type StraceParserImpl struct {
	lval  StraceSymType
	stack [StraceInitialStackSize]StraceSymType
	char  int
}

func (p *StraceParserImpl) Lookahead() int {
	return p.char
}

func StraceNewParser() StraceParser {
	return &StraceParserImpl{}
}

const StraceFlag = -32768

func StraceTokname(c int) string {
	if c >= 1 && c-1 < len(StraceToknames) {
		if StraceToknames[c-1] != "" {
			return StraceToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func StraceStatname(s int) string {
	if s >= 0 && s < len(StraceStatenames) {
		if StraceStatenames[s] != "" {
			return StraceStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func StraceErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !StraceErrorVerbose {
		return "syntax error"
	}

	for _, e := range StraceErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + StraceTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(StracePact[state])
	for tok := TOKSTART; tok-1 < len(StraceToknames); tok++ {
		if n := base + tok; n >= 0 && n < StraceLast && int(StraceChk[int(StraceAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if StraceDef[state] == -2 {
		i := 0
		for StraceExca[i] != -1 || int(StraceExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; StraceExca[i] >= 0; i += 2 {
			tok := int(StraceExca[i])
			if tok < TOKSTART || StraceExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if StraceExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += StraceTokname(tok)
	}
	return res
}

func Stracelex1(lex StraceLexer, lval *StraceSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(StraceTok1[0])
		goto out
	}
	if char < len(StraceTok1) {
		token = int(StraceTok1[char])
		goto out
	}
	if char >= StracePrivate {
		if char < StracePrivate+len(StraceTok2) {
			token = int(StraceTok2[char-StracePrivate])
			goto out
		}
	}
	for i := 0; i < len(StraceTok3); i += 2 {
		token = int(StraceTok3[i+0])
		if token == char {
			token = int(StraceTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(StraceTok2[1]) /* unknown char */
	}
	if StraceDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", StraceTokname(token), uint(char))
	}
	return char, token
}

func StraceParse(Stracelex StraceLexer) int {
	return StraceNewParser().Parse(Stracelex)
}

func (Stracercvr *StraceParserImpl) Parse(Stracelex StraceLexer) int {
	var Stracen int
	var StraceVAL StraceSymType
	var StraceDollar []StraceSymType
	_ = StraceDollar // silence set and not used
	StraceS := Stracercvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	Stracestate := 0
	Stracercvr.char = -1
	Stracetoken := -1 // Stracercvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		Stracestate = -1
		Stracercvr.char = -1
		Stracetoken = -1
	}()
	Stracep := -1
	goto Stracestack

ret0:
	return 0

ret1:
	return 1

Stracestack:
	/* put a state and value onto the stack */
	if StraceDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", StraceTokname(Stracetoken), StraceStatname(Stracestate))
	}

	Stracep++
	if Stracep >= len(StraceS) {
		nyys := make([]StraceSymType, len(StraceS)*2)
		copy(nyys, StraceS)
		StraceS = nyys
	}
	StraceS[Stracep] = StraceVAL
	StraceS[Stracep].yys = Stracestate

Stracenewstate:
	Stracen = int(StracePact[Stracestate])
	if Stracen <= StraceFlag {
		goto Stracedefault /* simple state */
	}
	if Stracercvr.char < 0 {
		Stracercvr.char, Stracetoken = Stracelex1(Stracelex, &Stracercvr.lval)
	}
	Stracen += Stracetoken
	if Stracen < 0 || Stracen >= StraceLast {
		goto Stracedefault
	}
	Stracen = int(StraceAct[Stracen])
	if int(StraceChk[Stracen]) == Stracetoken { /* valid shift */
		Stracercvr.char = -1
		Stracetoken = -1
		StraceVAL = Stracercvr.lval
		Stracestate = Stracen
		if Errflag > 0 {
			Errflag--
		}
		goto Stracestack
	}

Stracedefault:
	/* default state action */
	Stracen = int(StraceDef[Stracestate])
	if Stracen == -2 {
		if Stracercvr.char < 0 {
			Stracercvr.char, Stracetoken = Stracelex1(Stracelex, &Stracercvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if StraceExca[xi+0] == -1 && int(StraceExca[xi+1]) == Stracestate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			Stracen = int(StraceExca[xi+0])
			if Stracen < 0 || Stracen == Stracetoken {
				break
			}
		}
		Stracen = int(StraceExca[xi+1])
		if Stracen < 0 {
			goto ret0
		}
	}
	if Stracen == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			Stracelex.Error(StraceErrorMessage(Stracestate, Stracetoken))
			Nerrs++
			if StraceDebug >= 1 {
				__yyfmt__.Printf("%s", StraceStatname(Stracestate))
				__yyfmt__.Printf(" saw %s\n", StraceTokname(Stracetoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for Stracep >= 0 {
				Stracen = int(StracePact[StraceS[Stracep].yys]) + StraceErrCode
				if Stracen >= 0 && Stracen < StraceLast {
					Stracestate = int(StraceAct[Stracen]) /* simulate a shift of "error" */
					if int(StraceChk[Stracestate]) == StraceErrCode {
						goto Stracestack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if StraceDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", StraceS[Stracep].yys)
				}
				Stracep--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if StraceDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", StraceTokname(Stracetoken))
			}
			if Stracetoken == StraceEofCode {
				goto ret1
			}
			Stracercvr.char = -1
			Stracetoken = -1
			goto Stracenewstate /* try again in the same state */
		}
	}

	/* reduction by production Stracen */
	if StraceDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", Stracen, StraceStatname(Stracestate))
	}

	Stracent := Stracen
	Stracept := Stracep
	_ = Stracept // guard against "declared and not used"

	Stracep -= int(StraceR2[Stracen])
	// Stracep is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if Stracep+1 >= len(StraceS) {
		nyys := make([]StraceSymType, len(StraceS)*2)
		copy(nyys, StraceS)
		StraceS = nyys
	}
	StraceVAL = StraceS[Stracep+1]

	/* consult goto table to find next state */
	Stracen = int(StraceR1[Stracen])
	Straceg := int(StracePgo[Stracen])
	Stracej := Straceg + StraceS[Stracep].yys + 1

	if Stracej >= StraceLast {
		Stracestate = int(StraceAct[Straceg])
	} else {
		Stracestate = int(StraceAct[Stracej])
		if int(StraceChk[Stracestate]) != -Stracen {
			Stracestate = int(StraceAct[Straceg])
		}
	}
	// dummy call; replaced with literal code
	switch Stracent {

	case 1:
		StraceDollar = StraceS[Stracept-4 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:63
		{
			StraceVAL.val_syscall = NewSyscall(-1, StraceDollar[1].data, StraceDollar[3].val_types, int64(-1), true, false)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 2:
		StraceDollar = StraceS[Stracept-5 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:66
		{
			StraceVAL.val_syscall = NewSyscall(-1, "tmp", nil, -1, true, true)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 3:
		StraceDollar = StraceS[Stracept-4 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:71
		{
			StraceVAL.val_syscall = NewSyscall(-1, StraceDollar[1].data, nil, -1, true, true)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 4:
		StraceDollar = StraceS[Stracept-6 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:76
		{
			StraceVAL.val_syscall = NewSyscall(-1, StraceDollar[1].data, nil, int64(StraceDollar[6].val_int), false, false)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 5:
		StraceDollar = StraceS[Stracept-8 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:82
		{
			StraceVAL.val_syscall = NewSyscall(-1, StraceDollar[1].data, nil, int64(StraceDollar[8].val_int), false, false)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 6:
		StraceDollar = StraceS[Stracept-5 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:87
		{
			StraceVAL.val_syscall = NewSyscall(-1, "tmp", StraceDollar[2].val_types, StraceDollar[5].val_ret_type, false, true)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 7:
		StraceDollar = StraceS[Stracept-10 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:89
		{
			StraceVAL.val_syscall = NewSyscall(-1, "tmp", StraceDollar[7].val_types, StraceDollar[10].val_ret_type, false, true)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 8:
		StraceDollar = StraceS[Stracept-5 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:91
		{
			StraceVAL.val_syscall = NewSyscall(-1, "tmp", StraceDollar[2].val_types, -1, false, true)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 9:
		StraceDollar = StraceS[Stracept-8 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:93
		{
			StraceVAL.val_syscall = NewSyscall(-1, "tmp", StraceDollar[2].val_types, StraceDollar[5].val_ret_type, false, true)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 10:
		StraceDollar = StraceS[Stracept-9 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:96
		{
			StraceVAL.val_syscall = NewSyscall(-1, "tmp", StraceDollar[2].val_types, StraceDollar[5].val_ret_type, false, true)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 11:
		StraceDollar = StraceS[Stracept-6 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:98
		{
			StraceVAL.val_syscall = NewSyscall(-1, StraceDollar[1].data, StraceDollar[3].val_types, StraceDollar[6].val_ret_type, false, false)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 12:
		StraceDollar = StraceS[Stracept-6 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:101
		{
			StraceVAL.val_syscall = NewSyscall(-1, StraceDollar[1].data, StraceDollar[3].val_types, -1, false, false)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 13:
		StraceDollar = StraceS[Stracept-10 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:104
		{
			StraceVAL.val_syscall = NewSyscall(-1, StraceDollar[1].data, StraceDollar[3].val_types, StraceDollar[6].val_ret_type, false, false)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 14:
		StraceDollar = StraceS[Stracept-9 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:107
		{
			StraceVAL.val_syscall = NewSyscall(-1, StraceDollar[1].data, StraceDollar[3].val_types, StraceDollar[6].val_ret_type, false, false)
			Stracelex.(*Stracelexer).result = StraceVAL.val_syscall
		}
	case 15:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:110
		{
			call := StraceDollar[2].val_syscall
			call.Pid = StraceDollar[1].val_int
			Stracelex.(*Stracelexer).result = call
		}
	case 16:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:113
		{
			StraceVAL.val_type = nil
		}
	case 17:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:114
		{
			StraceVAL.val_type = nil
		}
	case 18:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:117
		{
			StraceVAL.val_type = nil
		}
	case 19:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:118
		{
			StraceVAL.val_type = nil
		}
	case 20:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:119
		{
			StraceVAL.val_type = nil
		}
	case 21:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:120
		{
			StraceVAL.val_type = nil
		}
	case 22:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:121
		{
			StraceVAL.val_type = nil
		}
	case 23:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:122
		{
			StraceVAL.val_type = nil
		}
	case 24:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:123
		{
			StraceVAL.val_type = nil
		}
	case 25:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:124
		{
			StraceVAL.val_type = nil
		}
	case 26:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:125
		{
			StraceVAL.val_type = nil
		}
	case 27:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:126
		{
			StraceVAL.val_type = nil
		}
	case 28:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:127
		{
			StraceVAL.val_type = nil
		}
	case 29:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:130
		{
			StraceVAL.val_ret_type = StraceDollar[1].val_int
		}
	case 30:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:131
		{
			StraceVAL.val_ret_type = int64(StraceDollar[1].val_uint)
		}
	case 31:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:132
		{
			StraceVAL.val_ret_type = -1 * StraceDollar[2].val_int
		}
	case 32:
		StraceDollar = StraceS[Stracept-0 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:135
		{
			StraceVAL.val_types = []IrType{}
		}
	case 33:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:136
		{
			StraceDollar[1].val_types = append(StraceDollar[1].val_types, StraceDollar[3].val_type)
			StraceVAL.val_types = StraceDollar[1].val_types
		}
	case 34:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:137
		{
			StraceDollar[1].val_types = append(StraceDollar[1].val_types, StraceDollar[2].val_type)
			StraceVAL.val_types = StraceDollar[1].val_types
		}
	case 35:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:140
		{
			StraceVAL.val_type = StraceDollar[1].val_buf_type
		}
	case 36:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:141
		{
			StraceVAL.val_type = StraceDollar[1].val_type
		}
	case 37:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:142
		{
			StraceVAL.val_type = StraceDollar[1].val_group_type
		}
	case 38:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:143
		{
			StraceVAL.val_type = StraceDollar[1].val_constant
		}
	case 39:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:144
		{
			StraceDollar[2].val_group_type.Complement = true
			StraceVAL.val_type = StraceDollar[2].val_group_type
		}
	case 40:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:147
		{
			StraceVAL.val_constant = Constant(StraceDollar[1].val_int)
		}
	case 41:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:148
		{
			StraceVAL.val_constant = Constant(StraceDollar[1].val_uint)
		}
	case 42:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:149
		{
			StraceVAL.val_constant = Constant(uint64(0))
		}
	case 43:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:150
		{
			StraceVAL.val_constant = StraceDollar[1].val_constant | StraceDollar[3].val_constant
		}
	case 44:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:151
		{
			StraceVAL.val_constant = StraceDollar[2].val_constant
		}
	case 45:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:152
		{
			StraceVAL.val_constant = StraceDollar[1].val_constant & StraceDollar[3].val_constant
		}
	case 46:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:153
		{
			StraceVAL.val_constant = StraceDollar[1].val_constant << StraceDollar[3].val_constant
		}
	case 47:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:154
		{
			StraceVAL.val_constant = StraceDollar[1].val_constant >> StraceDollar[3].val_constant
		}
	case 48:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:155
		{
			StraceVAL.val_constant = StraceDollar[2].val_constant
		}
	case 49:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:156
		{
			StraceVAL.val_constant = StraceDollar[1].val_constant * StraceDollar[3].val_constant
		}
	case 50:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:157
		{
			StraceVAL.val_constant = StraceDollar[1].val_constant - StraceDollar[3].val_constant
		}
	case 51:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:158
		{
			StraceVAL.val_constant = StraceDollar[1].val_constant + StraceDollar[3].val_constant
		}
	case 52:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:159
		{
			StraceVAL.val_constant = ^StraceDollar[2].val_constant
		}
	case 53:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:160
		{
			StraceVAL.val_constant = Constant(-int64(StraceDollar[2].val_constant))
		}
	case 54:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:163
		{
			StraceVAL.val_group_type = newGroupType(StraceDollar[2].val_types)
		}
	case 55:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:164
		{
			StraceVAL.val_group_type = newGroupType(StraceDollar[2].val_types)
		}
	case 56:
		StraceDollar = StraceS[Stracept-4 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:165
		{
			StraceVAL.val_group_type = newGroupType(StraceDollar[2].val_types)
		}
	case 57:
		StraceDollar = StraceS[Stracept-4 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:166
		{
			StraceVAL.val_group_type = newBPFGroupType(StraceDollar[1].data, StraceDollar[3].val_types)
		}
	case 58:
		StraceDollar = StraceS[Stracept-0 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:169
		{
			StraceVAL.val_types = []IrType{}
		}
	case 59:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:170
		{
			StraceDollar[1].val_types = append(StraceDollar[1].val_types, StraceDollar[3].val_type)
			StraceVAL.val_types = StraceDollar[1].val_types
		}
	case 60:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:171
		{
			StraceDollar[1].val_types = append(StraceDollar[1].val_types, StraceDollar[2].val_type)
			StraceVAL.val_types = StraceDollar[1].val_types
		}
	case 61:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:174
		{
			StraceVAL.val_type = StraceDollar[1].val_constant
		}
	case 62:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:175
		{
			StraceVAL.val_type = StraceDollar[1].val_constant
		}
	case 63:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:176
		{
			StraceVAL.val_type = StraceDollar[3].val_type
		}
	case 64:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:179
		{
			var ok bool
			StraceVAL.val_constant, ok = bpfFlagConstant(StraceDollar[1].data)
			if !ok {
				Stracelex.Error("unknown symbolic BPF operand: " + StraceDollar[1].data)
				return 1
			}
		}
	case 65:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:187
		{
			StraceVAL.val_constant = StraceDollar[1].val_constant | StraceDollar[3].val_constant
		}
	case 66:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:188
		{
			StraceVAL.val_constant = StraceDollar[1].val_constant | StraceDollar[3].val_constant
		}
	case 67:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:189
		{
			StraceVAL.val_constant = StraceDollar[1].val_constant | StraceDollar[3].val_constant
		}
	case 68:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:192
		{
			StraceVAL.val_type = StraceDollar[3].val_type
		}
	case 69:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:193
		{
			StraceVAL.val_type = StraceDollar[3].val_type
		}
	case 70:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:194
		{
			StraceVAL.val_type = StraceDollar[3].val_type
		}
	case 71:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:195
		{
			StraceVAL.val_type = StraceDollar[1].val_type
		}
	case 72:
		StraceDollar = StraceS[Stracept-6 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:196
		{
			StraceVAL.val_type = StraceDollar[6].val_type
		}
	case 73:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:199
		{
			StraceVAL.val_buf_type = newBufferType(StraceDollar[1].data)
		}
	case 74:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:200
		{
			StraceVAL.val_buf_type = newBufferType(StraceDollar[1].data)
		}
	case 75:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:201
		{
			StraceVAL.val_buf_type = newBufferType(StraceDollar[1].data)
		}
	case 76:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:202
		{
			StraceVAL.val_buf_type = newBufferType(StraceDollar[1].data)
		}
	case 77:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line tools/syz-trace2syz/parser/strace.y:203
		{
			StraceVAL.val_buf_type = newBufferType(StraceDollar[1].data)
		}
	}
	goto Stracestack /* stack new state and value */
}
