// Copyright 2026 syzkaller project authors. All rights reserved.
// Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.

package csource

import (
	"bytes"
	"errors"
	"fmt"
	"slices"
	"strconv"
	"strings"

	"github.com/google/syzkaller/prog"
)

var ErrUnsupportedCSBNetwork = errors.New("unsupported CSB network topology")

// csbDialect adapts a normal syzkaller C reproducer for inclusion as one of
// several independently namespaced benchmark headers in a CSB translation unit.
type csbDialect struct {
	ctx *context
}

func (*csbDialect) validate() error {
	if len(NetOpsFDsConnect) != 0 && len(NetOpsFDsAccept) != 0 {
		return fmt.Errorf("%w: both client and server sequences", ErrUnsupportedCSBNetwork)
	}
	if acceptCalls > 1 {
		return fmt.Errorf("%w: multiple server sequences", ErrUnsupportedCSBNetwork)
	}
	var first []NetOpSize
	for _, fd := range sortedUint64AnyKeys(NetOpsFDsConnect) {
		if first == nil {
			first = NetOpsFDsConnect[fd]
		} else if !slices.Equal(first, NetOpsFDsConnect[fd]) {
			return fmt.Errorf("%w: different client sequences", ErrUnsupportedCSBNetwork)
		}
	}
	return nil
}

func (dialect *csbDialect) sandboxCall(name string, arg int) string {
	if name == "" {
		return "LOOPUNIQUE(ctx, op_id);"
	}
	args := []string{}
	if name == "android" {
		args = append(args, strconv.Itoa(arg))
	}
	args = append(args, "ctx")
	return "do_sandbox_" + name + "(" + strings.Join(args, ",") + ");"
}

func (dialect *csbDialect) sourceHeader() (string, string, error) {
	ctx := dialect.ctx
	header := "// autogenerated by syzkaller (https://github.com/google/syzkaller)\n" +
		"// clang-format off\n" +
		"#ifndef UNIQUE_ID\n#define UNIQUE_ID\n#endif\n" +
		"#define RESOLVE(x) x\n" +
		"#define BM_JOIN(a,b) a ## b\n" +
		"#define BM_CAT(a,b) BM_JOIN(a,b)\n" +
		"#define UNIQUE_ID_TOK_TOK(...) BM_CAT(__VA_OPT__(_),RESOLVE(UNIQUE_ID))\n" +
		"#define UNIQUE_ID_TOK RESOLVE(UNIQUE_ID_TOK_TOK(RESOLVE(UNIQUE_ID)))\n" +
		"#define UNIQUE_NAME(prefix, tok) BM_CAT(prefix,tok)\n" +
		"#define UNIQUE_VAR(var) UNIQUE_NAME(var, RESOLVE(UNIQUE_ID_TOK))\n" +
		"#define UNIQUE_FUNC(func) UNIQUE_NAME(func, RESOLVE(UNIQUE_ID_TOK))\n" +
		"#define UNIQUE_GOTO(mark) UNIQUE_NAME(mark, RESOLVE(UNIQUE_ID_TOK))\n" +
		"#define UNIQUE_STR_STR(str) #str\n" +
		"#define UNIQUE_STR() UNIQUE_STR_STR(RESOLVE(UNIQUE_ID))\n" +
		fmt.Sprintf("#define MMAP_OFFSET 0x%xul\n", ctx.target.DataOffset) +
		fmt.Sprintf("#define MMAP_LENGTH 0x%xul\n", ctx.target.NumPages*ctx.target.PageSize) +
		fmt.Sprintf("const static uint64_t UNIQUE_VAR(maxWriteBufferSize) = %dul;\n", ctx.opts.MaxWriteSize) +
		fmt.Sprintf("const static uint64_t UNIQUE_VAR(maxWriteBufferSizeAlignment) = %dul;\n", ctx.opts.MaxWriteSizeAlignment)
	metadata := ""
	connect, err := toStringArray(NetOpsFDsConnect)
	if err != nil {
		return "", "", err
	}
	header += fmt.Sprintf("const char* UNIQUE_VAR(netops_connect)[%d] = {%s};\n", len(NetOpsFDsConnect), connect)
	if connect != "" {
		metadata += fmt.Sprintf("CLIENT_SEQ=%s\n", connect)
	}
	accept, err := toStringArray(NetOpsFDsAccept)
	if err != nil {
		return "", "", err
	}
	header += fmt.Sprintf("const char* UNIQUE_VAR(netops_accept)[%d] = {%s};\n", len(NetOpsFDsAccept), accept)
	if accept != "" {
		metadata += fmt.Sprintf("SERVER_SEQ=%s\n", accept)
	}
	return header + "\n", metadata, nil
}

func (*csbDialect) traceEpilogue(w *bytes.Buffer, _ int, _ string, resultVar string, expected *int64) {
	success := resultVar + " != -1"
	if expected != nil && *expected < 0 {
		success = resultVar + " == -1"
	}
	fmt.Fprintf(w, "\tif (%s) { UNIQUE_VAR(ctx->num_succeeded)++; } else { "+
		"assert(!abort_on_fail); UNIQUE_VAR(ctx->num_failed)++; }\n", success)
}

func (*csbDialect) pseudoCallName(name string) string {
	if strings.HasPrefix(name, "syz_csb_") || name == "syz_reapply_affinity" {
		return fmt.Sprintf("UNIQUE_FUNC(%v)", name)
	}
	return name
}

func (*csbDialect) rewriteArgument(call prog.ExecCall, callName string, index int) (string, bool) {
	if csbSandboxDirfdArg(callName, index) {
		return "UNIQUE_VAR(ctx->dirfd)", true
	}
	if index == 1 {
		switch call.Meta.Name {
		case "connect$inet":
			return "UNIQUE_VAR(ctx->connect4_arg)", true
		case "bind$inet":
			return "UNIQUE_VAR(ctx->bind4_arg)", true
		case "connect$inet6":
			return "UNIQUE_VAR(ctx->connect6_arg)", true
		case "bind$inet6":
			return "UNIQUE_VAR(ctx->bind6_arg)", true
		}
		switch callName {
		case "write", "pwrite64", "send", "sendto":
			return "UNIQUE_VAR(ctx->writeBuffer)", true
		}
	}
	if index == 2 {
		switch call.Meta.Name {
		case "connect$inet":
			return "sizeof(*(UNIQUE_VAR(ctx->connect4_arg)))", true
		case "bind$inet":
			return "sizeof(*(UNIQUE_VAR(ctx->bind4_arg)))", true
		case "connect$inet6":
			return "sizeof(*(UNIQUE_VAR(ctx->connect6_arg)))", true
		case "bind$inet6":
			return "sizeof(*(UNIQUE_VAR(ctx->bind6_arg)))", true
		case "bind$unix":
			return "sizeof(sa_family_t)", true
		}
	}
	return "", false
}

func csbSandboxDirfdArg(callName string, arg int) bool {
	switch callName {
	case "renameat", "renameat2", "linkat":
		return arg == 0 || arg == 2
	case "symlinkat":
		return arg == 1
	case "readlinkat", "openat", "openat2", "faccessat", "faccessat2", "newfstatat",
		"unlinkat", "mkdirat", "mknodat", "fchownat", "fchmodat", "utimensat", "statx":
		return arg == 0
	}
	return false
}

func (dialect *csbDialect) pointerOffset(value uint64) string {
	min := dialect.ctx.sysTarget.DataOffset
	max := min + dialect.ctx.target.NumPages*dialect.ctx.target.PageSize
	if value >= min && value < max {
		return "+PTR_OFFSET"
	}
	return ""
}

func (*csbDialect) resultArrayName() string {
	return "UNIQUE_VAR(ctx->r)"
}

func (*csbDialect) rewriteExit(result []byte) []byte {
	result = bytes.ReplaceAll(result, []byte("UNIQUE_FUNC(doexit)("), []byte("exit("))
	result = bytes.ReplaceAll(result,
		[]byte("#include <fcntl.h> // Definition of AT_* constants.\n"),
		[]byte("#include <fcntl.h> /* Definition of AT_* constants */\n"))
	result = bytes.ReplaceAll(result,
		[]byte("\t\tif (unlink(filename))\n\t\t\texitf(\"unlink(%s) failed\", filename);\n"),
		[]byte("\t\tif (unlink(filename)) {\n\t\t\texitf(\"unlink(%s) failed\", filename);\n\t\t}\n"))
	result = bytes.ReplaceAll(result,
		[]byte("\twhile (rmdir(dir))\n\t\texitf(\"rmdir(%s) failed\", dir);\n"),
		[]byte("\twhile (rmdir(dir)) {\n\t\texitf(\"rmdir(%s) failed\", dir);\n\t}\n"))
	return rewriteFailureCalls(result, "\tassert(0);\n")
}

func (*csbDialect) finalize(result []byte) []byte {
	result = bytes.Replace(result, []byte("#include <fcntl.h>\n"), nil, 1)
	return bytes.Replace(result, []byte("#ifndef CSB_MAX_WAIT_MS\n"),
		[]byte("#include <fcntl.h> /* Definition of AT_* constants */\n#ifndef CSB_MAX_WAIT_MS\n"), 1)
}

func (*csbDialect) emitProgramBanner(*bytes.Buffer, bool) {
}

func (*csbDialect) emitUnusedResult(w *bytes.Buffer) {
	fmt.Fprintln(w, "\tV_UNUSED(res);")
}

func (*csbDialect) declareResults([]uint64) string {
	return ""
}

func (*csbDialect) assembleCalls(_ string, syscalls, declarations, closes string) (string, string) {
	return "", declarations + "\n" + syscalls + "\n" + closes
}
