// Copyright 2026 syzkaller project authors. All rights reserved.
// Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.

package csource

import (
	"bytes"
	"fmt"
	"regexp"
	"strconv"
	"strings"

	"github.com/google/syzkaller/prog"
)

// sourceDialect is the complete customization boundary between the upstream C
// reproducer and embedding formats. Keep format-specific policy here so that
// normal csource generation only depends on this small interface.
type sourceDialect interface {
	validate() error
	sandboxCall(name string, arg int) string
	sourceHeader() (string, string, error)
	traceEpilogue(w *bytes.Buffer, call int, cast, resultVar string, expected *int64)
	pseudoCallName(name string) string
	rewriteArgument(call prog.ExecCall, callName string, index int) (string, bool)
	pointerOffset(value uint64) string
	resultArrayName() string
	rewriteExit(result []byte) []byte
	finalize(result []byte) []byte
	emitProgramBanner(w *bytes.Buffer, trace bool)
	emitUnusedResult(w *bytes.Buffer)
	declareResults(vars []uint64) string
	assembleCalls(results, syscalls, declarations, closes string) (string, string)
}

func (*upstreamDialect) validate() error {
	return nil
}

type upstreamDialect struct {
	ctx *context
}

func newSourceDialect(ctx *context) sourceDialect {
	if ctx.opts.CSB {
		return &csbDialect{ctx: ctx}
	}
	return &upstreamDialect{ctx: ctx}
}

func (dialect *upstreamDialect) sandboxCall(name string, arg int) string {
	if name == "" {
		return "loop();"
	}
	args := []string{}
	if name == "android" {
		args = append(args, strconv.Itoa(arg))
	}
	return "do_sandbox_" + name + "(" + strings.Join(args, ",") + ");"
}

func (*upstreamDialect) sourceHeader() (string, string, error) {
	return "// autogenerated by syzkaller (https://github.com/google/syzkaller)\n\n", "", nil
}

func (*upstreamDialect) traceEpilogue(w *bytes.Buffer, call int, cast, resultVar string, _ *int64) {
	fmt.Fprintf(w, "\tfprintf(stderr, \"### call=%v errno=%%u\\n\", %v%s == -1 ? errno : 0);\n",
		call, cast, resultVar)
}

func (*upstreamDialect) pseudoCallName(name string) string {
	return name
}

func (*upstreamDialect) rewriteArgument(prog.ExecCall, string, int) (string, bool) {
	return "", false
}

func (*upstreamDialect) pointerOffset(uint64) string {
	return ""
}

func (*upstreamDialect) resultArrayName() string {
	return "r"
}

func (*upstreamDialect) rewriteExit(result []byte) []byte {
	result = bytes.ReplaceAll(result, []byte("UNIQUE_FUNC(doexit)("), []byte("exit("))
	result = bytes.ReplaceAll(result, []byte("doexit("), []byte("exit("))
	return rewriteFailureCalls(result, "\texit(1);\n")
}

func (*upstreamDialect) finalize(result []byte) []byte {
	return result
}

func rewriteFailureCalls(result []byte, replacement string) []byte {
	result = regexp.MustCompile(`\t*exitf\((.*\n)*?.*\);\n`).ReplaceAll(result, []byte(replacement))
	return regexp.MustCompile(`\t*fail(msg)?\((.*\n)*?.*\);\n`).ReplaceAll(result, []byte(replacement))
}

func (*upstreamDialect) emitProgramBanner(w *bytes.Buffer, trace bool) {
	fmt.Fprintf(w, "\tif (write(1, \"executing program\\n\", sizeof(\"executing program\\n\") - 1)) {}\n")
	if trace {
		fmt.Fprintf(w, "\tfprintf(stderr, \"### start\\n\");\n")
	}
}

func (*upstreamDialect) emitUnusedResult(*bytes.Buffer) {
}

func (*upstreamDialect) declareResults(vars []uint64) string {
	if len(vars) == 0 {
		return ""
	}
	var out strings.Builder
	fmt.Fprintf(&out, "uint64 r[%v] = {", len(vars))
	for index, value := range vars {
		if index != 0 {
			out.WriteString(", ")
		}
		fmt.Fprintf(&out, "0x%x", value)
	}
	out.WriteString("};\n")
	return out.String()
}

func (*upstreamDialect) assembleCalls(results, syscalls, _, _ string) (string, string) {
	return results, syscalls
}
